apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: leptos-ui
  name: leptos-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: leptos-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: leptos-ui
    spec:
      containers:
        - image: registry.digitalocean.com/integrated-systems-registry/integrated-systems/leptos:v0.6
          name: leptos-ui
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: integrated-systems-registry
status: {}
